services:
  engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: echecs_engine:latest
    environment:
      - MIX_ENV=prod
    volumes:
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["eval", "EchecsEngine.Simulation.run()"]
